# Generated by Django 3.2.4 on 2021-06-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_relationshipmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationshipManager',
        ),
    ]
